[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = espidf

build_type = debug


; ─────────────────────────────────────────────────────────────
; DEBUG PRIN ESP-PROG 2 / JTAG
; ─────────────────────────────────────────────────────────────

; La pornirea debugului nu face automat încă un upload.
debug_load_mode = manual

debug_tool = custom
debug_port = :3333
debug_init_break = thbreak app_main

debug_server =
    C:/Espressif/tools/openocd-esp32/v0.12.0-esp32-20260424/openocd-esp32/bin/openocd.exe
    -s
    C:/Espressif/tools/openocd-esp32/v0.12.0-esp32-20260424/openocd-esp32/share/openocd/scripts
    -f
    interface/esp_usb_bridge.cfg
    -f
    target/esp32s3.cfg

debug_server_ready_pattern = Listening on port 3333 for gdb connections

debug_init_cmds =
    define pio_reset_halt_target
        monitor reset halt
    end
    define pio_reset_run_target
        monitor reset
    end
    target extended-remote $DEBUG_PORT
    monitor reset halt
    $INIT_BREAK
    continue


; ─────────────────────────────────────────────────────────────
; UPLOAD PRIN ESP-PROG 2 / JTAG
; ─────────────────────────────────────────────────────────────

upload_protocol = custom

upload_command = C:/Espressif/tools/openocd-esp32/v0.12.0-esp32-20260424/openocd-esp32/bin/openocd.exe -s C:/Espressif/tools/openocd-esp32/v0.12.0-esp32-20260424/openocd-esp32/share/openocd/scripts -f interface/esp_usb_bridge.cfg -f target/esp32s3.cfg -c "program_esp .pio/build/esp32-s3-devkitm-1/firmware.bin 0x10000 verify reset exit"