[platformio]
default_envs = esp32-s3-devkitm-1

[openocd]
executable = C:/Espressif/tools/openocd-esp32/v0.12.0-esp32-20260424/openocd-esp32/bin/openocd.exe
scripts = C:/Espressif/tools/openocd-esp32/v0.12.0-esp32-20260424/openocd-esp32/share/openocd/scripts

[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = espidf
build_type = debug

; ESP32-S3-WROOM-1-N16R8: 16 MB flash + 8 MB octal PSRAM.
board_build.flash_size = 16MB
board_build.flash_mode = dio
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
board_upload.maximum_size = 4194304
board_build.esp-idf.sdkconfig_path = sdkconfig.esp32-s3-devkitm-1

; Debug prin ESP-PROG 2 / JTAG.
; Pornirea depanarii nu declanseaza automat un upload.
debug_load_mode = manual
debug_tool = custom
debug_port = :3333
debug_init_break = thbreak app_main

debug_server =
    ${openocd.executable}
    -s
    ${openocd.scripts}
    -f
    interface/esp_usb_bridge.cfg
    -f
    target/esp32s3.cfg

debug_server_ready_pattern = Listening on port 3333 for gdb connections

debug_init_cmds =
    define pio_reset_halt_target
        monitor reset halt
    end
    define pio_reset_run_target
        monitor reset
    end
    target extended-remote $DEBUG_PORT
    monitor reset halt
    $INIT_BREAK
    continue

; Upload rapid prin JTAG: rescrie doar partitia aplicatiei.
upload_protocol = custom
upload_command = ${openocd.executable} -s ${openocd.scripts} -f interface/esp_usb_bridge.cfg -f target/esp32s3.cfg -c "program_esp .pio/build/$PIOENV/firmware.bin 0x10000 verify reset exit"

[env:esp32-s3-devkitm-1-full]
extends = env:esp32-s3-devkitm-1

; Upload complet prin JTAG: bootloader + tabela de partitii + aplicatie.
upload_command = ${openocd.executable} -s ${openocd.scripts} -f interface/esp_usb_bridge.cfg -f target/esp32s3.cfg -c "program_esp .pio/build/$PIOENV/bootloader.bin 0x0 verify" -c "program_esp .pio/build/$PIOENV/partitions.bin 0x8000 verify" -c "program_esp .pio/build/$PIOENV/firmware.bin 0x10000 verify reset exit"
